{% set version = "4.13.2" %}

package:
  name: antlr4-cli
  version: {{ version }}

source:
  url: https://github.com/twiinit/antlr4-cli/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b9c1c35a712cb088c2370f15b51a52901b4a61d7b9f0d82f1fce586322f282a7

build:
  number: 0
  noarch: python
  script: pip install --no-deps .
  entry_points:
    - antlr4=antlr4_cli:tool
    - antlr4-parse=antlr4_cli:interp
  
requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - openjdk
    - python >=3.6

test:
  commands:
    - antlr4
    - antlr4-parse

about:
  home: https://github.com/twiinit/antlr4-cli
  license: BSD-3-Clause
  license_file: LICENSE
  summary: ANTLR4 CLI to interface with Java distribution

extra:
  recipe-maintainers:
    - adriendelsalle
